title: yavuz_ertugrul@home:~/blog$
description: "Blog by a programming, ML, Robotics enthusiast"
author:
  name: "Yavuz"
  email: "yavuz.coding@gmail.com"
  url: "https://www.yavuzertugrul.com"

baseurl: /
url: "https://www.yavuzertugrul.com"

source: .
destination: ./_site
permalink: /:title
paginate: 10
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Yavuz"
year : "2024"

baseurl: "" # If your site is at the root, otherwise set the subpath

# collections:
#   sketches:
#     output: true

collections:
  thoughts:
    output: true

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    inline_theme: github
    block_theme: github
